/**
 * Codex App Server JSON-RPC protocol types.
 *
 * Declares only the types the adapter actually uses, with shapes strictly aligned to the bindings
 * generated by `codex app-server generate-ts --experimental` (top-level + v2/). Codex-private
 * vocabulary (thread/turn/item/dynamicTools/sandboxPolicy, etc) is confined to the codex adapter
 * directory and does not leak into the common types.
 *
 * Shapes mirror `codex app-server generate-ts --experimental` @ codex-cli 0.133.0; re-generate to verify.
 */

// ---- Base aliases (the generated bindings' JsonValue / RequestId / AbsolutePathBuf, etc) ----

/** serde_json::Value -- arbitrary JSON. Appears as `JsonValue` in the generated bindings (e.g. dynamicTools.inputSchema / inject items). */
export type JsonValue = unknown;
/** JSON-RPC id: string | number (top-level RequestId.ts). */
export type RequestId = string | number;
/** AbsolutePathBuf is a string on the wire. */
export type AbsolutePathBuf = string;

// ---- initialize handshake (top-level InitializeParams / InitializeResponse / InitializeCapabilities / ClientInfo) ----

export interface ClientInfo {
  name: string;
  title: string | null;
  version: string;
}

export interface InitializeCapabilities {
  experimentalApi: boolean;
  requestAttestation: boolean;
  optOutNotificationMethods?: Array<string> | null;
}

export interface InitializeParams {
  clientInfo: ClientInfo;
  capabilities: InitializeCapabilities | null;
}

export interface InitializeResponse {
  userAgent: string;
  /** Absolute path to the server's $CODEX_HOME directory (compared by the self-check). */
  codexHome: AbsolutePathBuf;
  platformFamily: string;
  platformOs: string;
}

// ---- sandbox / approval / reasoning (v2/SandboxPolicy / AskForApproval / ReasoningEffort / ReasoningSummary) ----

/** v2/SandboxPolicy (workspaceWrite.writableRoots is where the isolation writable roots land). */
export type SandboxPolicy =
  | { type: "dangerFullAccess" }
  | { type: "readOnly"; networkAccess: boolean }
  | { type: "externalSandbox"; networkAccess: NetworkAccess }
  | {
      type: "workspaceWrite";
      writableRoots: Array<AbsolutePathBuf>;
      networkAccess: boolean;
      excludeTmpdirEnvVar: boolean;
      excludeSlashTmp: boolean;
    };

/** v2/NetworkAccess (used by externalSandbox; the wire shape is conservatively declared as an open union). */
export type NetworkAccess = "enabled" | "disabled" | (string & {});

/** v2/AskForApproval -- "never" is used for unattended automation. */
export type AskForApproval =
  | "untrusted"
  | "on-failure"
  | "on-request"
  | { granular: { sandbox_approval: boolean; rules: boolean; skill_approval: boolean; request_permissions: boolean; mcp_elicitations: boolean } }
  | "never";

/** ReasoningEffort (top-level). */
export type ReasoningEffort = "none" | "minimal" | "low" | "medium" | "high" | "xhigh";
/** ReasoningSummary (top-level). */
export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

// ---- Thread / Turn / items (v2/Thread / Turn / ThreadItem / UserInput) ----

export type TurnStatus = "completed" | "interrupted" | "failed" | "inProgress";

/** v2/CodexErrorInfo -- a camelCase error-code union (some variants carry httpStatusCode). */
export type CodexErrorInfo =
  | "contextWindowExceeded"
  | "usageLimitExceeded"
  | "serverOverloaded"
  | "cyberPolicy"
  | { httpConnectionFailed: { httpStatusCode: number | null } }
  | { responseStreamConnectionFailed: { httpStatusCode: number | null } }
  | "internalServerError"
  | "unauthorized"
  | "badRequest"
  | "threadRollbackFailed"
  | "sandboxError"
  | { responseStreamDisconnected: { httpStatusCode: number | null } }
  | { responseTooManyFailedAttempts: { httpStatusCode: number | null } }
  | { activeTurnNotSteerable: { turnKind: string } }
  | "other";

export interface TurnError {
  message: string;
  codexErrorInfo: CodexErrorInfo | null;
  additionalDetails: string | null;
}

/** v2/UserInput -- the input elements for turn/start / turn/steer (the adapter only produces text / image / localImage). */
export type UserInput =
  | { type: "text"; text: string; text_elements: Array<JsonValue> }
  | { type: "image"; detail?: JsonValue; url: string }
  | { type: "localImage"; detail?: JsonValue; path: string }
  | { type: "skill"; name: string; path: string }
  | { type: "mention"; name: string; path: string };

/** v2/ThreadItem -- the item union (the variants the adapter uses; the rest go to provider_raw, hence the open trailing item). */
export type ThreadItem =
  | { type: "userMessage"; id: string; content: Array<UserInput> }
  | { type: "agentMessage"; id: string; text: string; phase: JsonValue | null; memoryCitation: JsonValue | null }
  | { type: "plan"; id: string; text: string }
  | { type: "reasoning"; id: string; summary: Array<string>; content: Array<string> }
  | {
      type: "commandExecution";
      id: string;
      command: string;
      cwd: AbsolutePathBuf;
      processId: string | null;
      status: string;
      aggregatedOutput: string | null;
      exitCode: number | null;
      durationMs: number | null;
    }
  | { type: "fileChange"; id: string; changes: Array<JsonValue>; status: string }
  | {
      type: "mcpToolCall";
      id: string;
      server: string;
      tool: string;
      status: string;
      arguments: JsonValue;
      pluginId: string | null;
      result: JsonValue | null;
      error: JsonValue | null;
      durationMs: number | null;
    }
  | {
      type: "dynamicToolCall";
      id: string;
      namespace: string | null;
      tool: string;
      arguments: JsonValue;
      status: DynamicToolCallStatus;
      contentItems: Array<DynamicToolCallOutputContentItem> | null;
      success: boolean | null;
      durationMs: number | null;
    }
  | { type: "webSearch"; id: string; query: string; action: JsonValue | null }
  | { type: "contextCompaction"; id: string };
// Undeclared item variants (imageView / collabAgentToolCall / enteredReviewMode, etc) fall through to
// ProviderRaw in the normalizer; the ThreadItem union only lists named variants (to avoid an open index
// signature polluting narrowing of the named variants). ItemStarted/Completed.item may be an unlisted
// variant at runtime, but the normalizer's default branch handles it as `provider_raw`, so the union
// does not need to be opened up at the type level.

export interface Turn {
  id: string;
  items: Array<ThreadItem>;
  itemsView: JsonValue;
  status: TurnStatus;
  error: TurnError | null;
  startedAt: number | null;
  completedAt: number | null;
  durationMs: number | null;
}

export interface Thread {
  id: string;
  sessionId: string;
  cwd: AbsolutePathBuf;
  turns: Array<Turn>;
  [k: string]: unknown;
}

// ---- dynamicTools (v2/DynamicToolSpec / DynamicToolCallParams / DynamicToolCallResponse / *Status / *OutputContentItem) ----

export interface DynamicToolSpec {
  namespace?: string;
  name: string;
  description: string;
  inputSchema: JsonValue;
  deferLoading?: boolean;
}

export type DynamicToolCallStatus = "inProgress" | "completed" | "failed";

export type DynamicToolCallOutputContentItem =
  | { type: "inputText"; text: string }
  | { type: "inputImage"; imageUrl: string };

/** Params for the `item/tool/call` ServerRequest. */
export interface DynamicToolCallParams {
  threadId: string;
  turnId: string;
  callId: string;
  namespace: string | null;
  tool: string;
  arguments: JsonValue;
}

/** The response for `item/tool/call` (the result returned by the host handler). */
export interface DynamicToolCallResponse {
  contentItems: Array<DynamicToolCallOutputContentItem>;
  success: boolean;
}

// ---- lifecycle request params / results (v2/ThreadStartParams, etc) ----

export interface ThreadStartParams {
  model?: string | null;
  cwd?: string | null;
  approvalPolicy?: AskForApproval | null;
  sandbox?: SandboxMode | null;
  config?: { [key: string]: JsonValue } | null;
  baseInstructions?: string | null;
  developerInstructions?: string | null;
  dynamicTools?: Array<DynamicToolSpec> | null;
  experimentalRawEvents: boolean;
  persistExtendedHistory: boolean;
  [k: string]: unknown;
}

export type SandboxMode = "read-only" | "workspace-write" | "danger-full-access";

export interface ThreadStartResponse {
  thread: Thread;
  model: string;
  modelProvider: string;
  cwd: AbsolutePathBuf;
  [k: string]: unknown;
}

export interface ThreadResumeParams {
  threadId: string;
  cwd?: string | null;
  [k: string]: unknown;
}

export interface ThreadResumeResponse {
  thread: Thread;
  [k: string]: unknown;
}

export interface TurnStartParams {
  threadId: string;
  input: Array<UserInput>;
  cwd?: string | null;
  approvalPolicy?: AskForApproval | null;
  sandboxPolicy?: SandboxPolicy | null;
  model?: string | null;
  effort?: ReasoningEffort | null;
  summary?: ReasoningSummary | null;
  outputSchema?: JsonValue | null;
  [k: string]: unknown;
}

export interface TurnStartResponse {
  turn: Turn;
}

export interface TurnSteerParams {
  threadId: string;
  input: Array<UserInput>;
  /** Must equal the current active turn id, otherwise the server rejects it. */
  expectedTurnId: string;
}

export interface TurnSteerResponse {
  turnId: string;
}

export interface TurnInterruptParams {
  threadId: string;
  turnId: string;
}

export type TurnInterruptResponse = Record<string, never>;

export interface ThreadUnsubscribeParams {
  threadId: string;
}

export type ThreadUnsubscribeStatus = "notLoaded" | "notSubscribed" | "unsubscribed";

export interface ThreadUnsubscribeResponse {
  status: ThreadUnsubscribeStatus;
}

export interface ThreadCompactStartParams {
  threadId: string;
}

export type ThreadCompactStartResponse = Record<string, never>;

export interface ThreadInjectItemsParams {
  threadId: string;
  items: Array<JsonValue>;
}

export type ThreadInjectItemsResponse = Record<string, never>;

// ---- server-to-client notifications (v2/*Notification) ----

export interface ThreadStartedNotification {
  thread: Thread;
}

export interface TurnStartedNotification {
  threadId: string;
  turn: Turn;
}

export interface TurnCompletedNotification {
  threadId: string;
  turn: Turn;
}

export interface ItemStartedNotification {
  item: ThreadItem;
  threadId: string;
  turnId: string;
  startedAtMs: number;
}

export interface ItemCompletedNotification {
  item: ThreadItem;
  threadId: string;
  turnId: string;
  completedAtMs: number;
}

export interface AgentMessageDeltaNotification {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
}

export interface ReasoningTextDeltaNotification {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
  contentIndex: number;
}

export interface ReasoningSummaryTextDeltaNotification {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
  summaryIndex: number;
}

export interface TokenUsageBreakdown {
  totalTokens: number;
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  reasoningOutputTokens: number;
}

export interface ThreadTokenUsage {
  total: TokenUsageBreakdown;
  last: TokenUsageBreakdown;
  modelContextWindow: number | null;
}

export interface ThreadTokenUsageUpdatedNotification {
  threadId: string;
  turnId: string;
  tokenUsage: ThreadTokenUsage;
}

/** Deprecated alias of the `contextCompaction` item; retained to tolerate older app-servers. */
export interface ContextCompactedNotification {
  threadId: string;
  turnId: string;
}

export interface ErrorNotification {
  error: TurnError;
  willRetry: boolean;
  threadId: string;
  turnId: string;
}

// ---- JSON-RPC envelopes ----

export interface JsonRpcRequest {
  jsonrpc: "2.0";
  id: RequestId;
  method: string;
  params?: JsonValue;
}

export interface JsonRpcResponseOk {
  jsonrpc: "2.0";
  id: RequestId;
  result: JsonValue;
}

export interface JsonRpcResponseErr {
  jsonrpc: "2.0";
  id: RequestId;
  error: { code: number; message: string; data?: JsonValue };
}

export type JsonRpcResponse = JsonRpcResponseOk | JsonRpcResponseErr;

export interface JsonRpcNotification {
  jsonrpc: "2.0";
  method: string;
  params?: JsonValue;
}

/** A server-to-client message (either a notification or a request that requires a response). */
export type ServerInbound = JsonRpcRequest | JsonRpcResponse | JsonRpcNotification;

// ---- JSON-RPC method name constants (client-to-server) ----

export const CLIENT_METHODS = {
  initialize: "initialize",
  threadStart: "thread/start",
  threadResume: "thread/resume",
  threadCompactStart: "thread/compact/start",
  threadInjectItems: "thread/inject_items",
  threadUnsubscribe: "thread/unsubscribe",
  turnStart: "turn/start",
  turnSteer: "turn/steer",
  turnInterrupt: "turn/interrupt",
} as const;

/** server-to-client notification method names (the source for eventNormalize mapping). */
export const NOTIFICATION_METHODS = {
  threadStarted: "thread/started",
  turnStarted: "turn/started",
  turnCompleted: "turn/completed",
  itemStarted: "item/started",
  itemCompleted: "item/completed",
  agentMessageDelta: "item/agentMessage/delta",
  reasoningTextDelta: "item/reasoning/textDelta",
  reasoningSummaryTextDelta: "item/reasoning/summaryTextDelta",
  tokenUsageUpdated: "thread/tokenUsage/updated",
  threadCompacted: "thread/compacted",
  turnDiffUpdated: "turn/diff/updated",
  error: "error",
} as const;

/** server-to-client request method names (require a response: tool call / approvals / token refresh). */
export const SERVER_REQUEST_METHODS = {
  itemToolCall: "item/tool/call",
  itemToolRequestUserInput: "item/tool/requestUserInput",
  execCommandApproval: "execCommandApproval",
  applyPatchApproval: "applyPatchApproval",
  commandExecutionRequestApproval: "item/commandExecution/requestApproval",
  fileChangeRequestApproval: "item/fileChange/requestApproval",
  permissionsRequestApproval: "item/permissions/requestApproval",
  mcpElicitationRequest: "mcpServer/elicitation/request",
  chatgptAuthTokensRefresh: "account/chatgptAuthTokens/refresh",
} as const;
